### ISSUE TITLE
crash in monitoring for PrimeX

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/halld_recon#116]
The latest monitoring runs all crashed with the same error:

```
JANA >>Reading CCAL profile data from /group/halld/www/halldweb/html/resources//CCAL/profile_data/ccal_profile_data_v1.dat ...
At line 27 of file libraries/CCAL/island.F (unit = 22, file = '�')
Fortran runtime error: File '/group/halld/www/halldweb/html/resources//CCAL/profile_data/ccal_profile_data_v1.dat^' does not exist
```
I reproduced the error with the file
/cache/halld/RunPeriod-2019-01/rawdata/Run061260/hd_rawdata_061260_000.evio

**Comment by sdobbs** [comment]
Could you please point to a log file?  This should be loaded as a resource...

On Mon, Feb 25, 2019 at 10:19 AM Alex Austregesilo <notifications@github.com<mailto:notifications@github.com>> wrote:

The latest monitoring runs all crashed with the same error:

JANA >>Reading CCAL profile data from /group/halld/www/halldweb/html/resources//CCAL/profile_data/ccal_profile_data_v1.dat ...

At line 27 of file libraries/CCAL/island.F (unit = 22, file = '�')

Fortran runtime error: File '/group/halld/www/halldweb/html/resources//CCAL/profile_data/ccal_profile_data_v1.dat^' does not exist



I reproduced the error with the file
/cache/halld/RunPeriod-2019-01/rawdata/Run061260/hd_rawdata_061260_000.evio

**Comment by aaust** [comment]
/work/halld2/data_monitoring/RunPeriod-2019-01/mon_ver01/log/061260/stdout.061260_000.out
/work/halld2/data_monitoring/RunPeriod-2019-01/mon_ver01/log/061260/stderr.061260_000.err

**Comment by sdobbs** [comment]
yeah this is a memory error - a fix exists, I'll get it

**Comment by sdobbs** [comment]
should be fixed by #118

**Comment by aaust** [comment]
sorry, it isn't

**Comment by sdobbs** [comment]
#119 should fix it.  there are a bunch of warning messages which need to be limited, but we can run at least

**Comment by aaust** [comment]
There is a massive amount of warning messages, and then it still crashes

**Comment by sdobbs** [comment]
OK, I commented out the worst warning and cleared things up.  This works for some other files, so I would go ahead and use this for now.

Keep the issue open, we are working to get rid of global variables and other nasty memory management issues...

**Comment by aaust** [comment]
Ok thanks, I don't see a crash with the file mentioned above. Just a few messages like:

> WRN bad cluster log. coord, center id = 85 322.500000
